import type { ArtifactOut } from "./endpoints";

/**
 * Dev-only mock of the agent artifacts endpoint (`GET /agent/{id}/artifacts`).
 * The local mock agent stream (`mockAgent.ts`) produces no real files, so the
 * ArtifactViewer needs a stand-in to be demoable without the live LangGraph
 * backend. Gated by the same VITE_MOCK_AGENT flag as the stream (`env.mockAgent`).
 * FUTURE: delete once the agent runtime is runnable locally.
 */
const MOCK_ARTIFACTS: ArtifactOut[] = [
  {
    file_id: "mock-plan",
    name: "plan.md",
    language: "markdown",
    mime_type: "text/markdown",
    content: [
      "# Migration plan",
      "",
      "1. Snapshot the `orders` table.",
      "2. Backfill the `region` column from `customers`.",
      "3. Add the partial index `idx_orders_open`.",
      "4. Cut over reads behind the `orders_v2` flag.",
      "",
      "> Generated by the agent run — read-only preview.",
    ].join("\n"),
  },
  {
    file_id: "mock-backfill",
    name: "backfill.py",
    language: "python",
    mime_type: "text/x-python",
    content: [
      "import asyncio",
      "",
      "import asyncpg",
      "",
      "",
      "async def backfill_region(pool: asyncpg.Pool, batch: int = 500) -> int:",
      '    """Copy customers.region onto orders in bounded batches."""',
      "    moved = 0",
      "    while True:",
      "        rows = await pool.fetch(",
      '            "UPDATE orders o SET region = c.region "',
      '            "FROM customers c WHERE c.id = o.customer_id "',
      '            "AND o.region IS NULL "',
      '            "AND o.id IN (SELECT id FROM orders WHERE region IS NULL LIMIT $1) "',
      '            "RETURNING o.id",',
      "            batch,",
      "        )",
      "        if not rows:",
      "            return moved",
      "        moved += len(rows)",
      "        await asyncio.sleep(0)  # yield between batches",
    ].join("\n"),
  },
  {
    file_id: "mock-summary",
    name: "result.json",
    language: "json",
    mime_type: "application/json",
    content: JSON.stringify(
      {
        status: "completed",
        steps: 4,
        rows_backfilled: 18432,
        index_created: "idx_orders_open",
        warnings: [],
      },
      null,
      2,
    ),
  },
];

export function mockListArtifacts(): Promise<ArtifactOut[]> {
  return Promise.resolve(MOCK_ARTIFACTS);
}
