"""Agent API schemas.

Includes request payload parameters and Monaco-compatible file metadata definitions.
"""

from __future__ import annotations

from datetime import datetime
from pydantic import BaseModel, Field


class AgentRunRequest(BaseModel):
    """Payload to initiate a new autonomous agent diagnostic run."""

    prompt: str = Field(
        ...,
        min_length=1,
        max_length=8192,
        description="The query, error traceback, or task instruction for the agent.",
    )
    peer_agent_ids: list[str] = Field(
        default_factory=list,
        description="Optional A2A peer agent targets (ignored in Phase 1 stub).",
    )


class AgentSessionOut(BaseModel):
    """Metadata response representing a running or completed agent session."""

    agent_session_id: str
    session_id: str
    status: str
    truncated: bool = False
    started_at: datetime | None = None
    ended_at: datetime | None = None


class ArtifactOut(BaseModel):
    """Monaco-editor-compatible code file generated by the agent."""

    file_id: str
    name: str
    content: str
    language: str | None = None
    mime_type: str = "text/plain"
