"""ManageArtifactsUseCase — listings and retrieval operations for code/text files.

Fetches data references from Postgres (Monaco code display details).
"""

from __future__ import annotations

import logging
from typing import Any

from core.ports.store import StorePort

logger = logging.getLogger(__name__)


class ManageArtifactsUseCase:
    """Handles retrieving code artifacts generated by agent runs."""

    def __init__(self, store: StorePort) -> None:
        self._store = store

    async def list_artifacts(self, *, agent_session_id: str, tenant_id: str) -> list[dict[str, Any]]:
        """List metadata references for files generated within an agent session."""
        rows = await self._store.list_artifacts(
            agent_session_id=agent_session_id,
            tenant_id=tenant_id,
        )
        # Parse fields dynamically and map to dict structures
        results = []
        for r in rows:
            # Monaco code highlight file hints
            name = str(r.get("name", ""))
            language = self._detect_language(name)
            results.append({
                "file_id": r.get("file_id", ""),
                "agent_session_id": r.get("agent_session_id", ""),
                "name": name,
                "content": r.get("content", ""),
                "language": language,
                "mime_type": self._detect_mime(language),
            })
        return results

    async def get_artifact(self, *, file_id: str, tenant_id: str) -> dict[str, Any] | None:
        """Fetch a specific code file by identifier."""
        r = await self._store.get_artifact(file_id=file_id, tenant_id=tenant_id)
        if not r:
            return None
        name = str(r.get("name", ""))
        language = self._detect_language(name)
        return {
            "file_id": r.get("file_id", ""),
            "agent_session_id": r.get("agent_session_id", ""),
            "name": name,
            "content": r.get("content", ""),
            "language": language,
            "mime_type": self._detect_mime(language),
        }

    def _detect_language(self, name: str) -> str:
        """Infer Monaco editor highlighting parser language based on file extension."""
        ext = name.split(".")[-1].lower() if "." in name else ""
        mapping = {
            "py": "python",
            "json": "json",
            "js": "javascript",
            "ts": "typescript",
            "sql": "sql",
            "html": "html",
            "css": "css",
            "sh": "shell",
            "md": "markdown",
        }
        return mapping.get(ext, "plaintext")

    def _detect_mime(self, language: str) -> str:
        """Match standard MIME types."""
        mapping = {
            "python": "text/x-python",
            "json": "application/json",
            "javascript": "application/javascript",
            "typescript": "application/typescript",
            "sql": "text/x-sql",
            "html": "text/html",
            "css": "text/css",
            "shell": "text/x-shellscript",
            "markdown": "text/markdown",
        }
        return mapping.get(language, "text/plain")
