# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adapters/retriever/model_server/proto/embedding.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'adapters/retriever/model_server/proto/embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5adapters/retriever/model_server/proto/embedding.proto\x12\tembedding\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"/\n\x0cSparseVector\x12\x0f\n\x07indices\x18\x01 \x03(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02\"K\n\x11\x45mbeddingResponse\x12\r\n\x05\x64\x65nse\x18\x01 \x03(\x02\x12\'\n\x06sparse\x18\x02 \x01(\x0b\x32\x17.embedding.SparseVector2]\n\x10\x45mbeddingService\x12I\n\x0cGetEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adapters.retriever.model_server.proto.embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=68
  _globals['_EMBEDDINGREQUEST']._serialized_end=100
  _globals['_SPARSEVECTOR']._serialized_start=102
  _globals['_SPARSEVECTOR']._serialized_end=149
  _globals['_EMBEDDINGRESPONSE']._serialized_start=151
  _globals['_EMBEDDINGRESPONSE']._serialized_end=226
  _globals['_EMBEDDINGSERVICE']._serialized_start=228
  _globals['_EMBEDDINGSERVICE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
